### ISSUE TITLE
Firefox Support?

### ISSUE THREAD

**Issue by Flalaski** [multimediamike/SaltyGME#4]
Hello,

laymen here, I love this extension and happily use it on Chrome. that said, is a Firefox Add-on planned for this / very doable without rebuilding from scratch?

Cheers.

**Comment by multimediamike** [comment]
I have something better for you: A pure JavaScript version of the same thing (though I'm still working on NDS, Saturn, and Dreamcast soundtracks). Works great in Firefox, Safari, and Edge too. Visit Cirrus Retro:

https://cirrusretro.com/

If you're interested in the source code, you can find it here:

https://github.com/multimediamike/cirrusretro-players

Thanks for reminding me that I should update this project's README to point to the JS-based project.

**Comment by Flalaski** [comment]
Amazing! Works on my phone as well, which is super handy. Thanks!
