### ISSUE TITLE
Pausing Bug

### ISSUE THREAD

**Issue by Xarnax42** [multimediamike/SaltyGME#5]
I was browsing through some tracks just now and noticed that sometimes the "Play" button would not change to "Pause".  It seems this happens when you Pause a track and then Navigate to a new one without unpausing first.

**Comment by multimediamike** [comment]
I don't really maintain the NaCl version of the players anymore. I have a pure-JS version now at https://cirrusretro.com/. Does the problem still manifest there?

**Comment by Xarnax42** [comment]
I did see the JS version mentioned in other issue threads, and the problem doesn't seem to exist there. Figured I'd mention it just in case, as this extension appears to support a couple libraries that Cirrus Retro does not.

**Comment by multimediamike** [comment]
This is true, and something I am working on (trying to get the other playback libraries incorporated into CR).

**Comment by Xarnax42** [comment]
Well I appreciate your responses. I don't know how many ever remember, but I try to steer people towards your work often.  It's an awesome project, and I greatly appreciate all the work you've put into it.

**Comment by multimediamike** [comment]
Thanks! Feedback like this makes it worthwhile. :-)
